name: Say hello

on:
    push:
        branches: 
            - main


jobs:
    hello_world:
        runs-on: ubuntu-18.4
        steps:
            - name: Echo the message
              run: |
                echo "Hola, Saúl"