name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
              with:
                fetch-depth: 1
            - uses: actions/setup-node@v3
              with:
                node-version: 19
            - name: Install dependencies
              run: npm install
            - name: Lint
              run: npm run lint